name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    tags:
      - '*'
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Latest Tag
      uses: WyriHaximus/github-action-get-previous-tag@v1

      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
