name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    tags:
      - '*'
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current tag
      id: get-current-tag
      uses: zingimmick/github-action-get-current-tag@v1
    - name: Print tag
      run: echo ${{steps.get-current-tag.outputs.tag}}
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
